---
title: Morgan Tracey
timezone: America/Phoenix
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: The personal website of Morgan Tracey, US skeleton athlete, attorney,
  and wildland firefighter
url: https://morgantracey.github.io
locale: en
markdown: kramdown
permalink: "/:title"
show-social-links-in-footer: true
include:
- _pages
exclude:
- LICENSE
- README.md
- Gemfile
- Gemfile.lock
