---
title: Skeleton Theme
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: kyle@kyletress.com
description: Skeleton, a minimal web theme for Jekyll
url: https://kyletress.github.io
locale: en
markdown: kramdown
permalink: "/:title"
tagline: Minimal skeleton theme
show-social-links-in-footer: true
show-share-buttons: true
quote: Carpe Diem
include:
- _pages
exclude:
- LICENSE
- README.md
- Gemfile
- Gemfile.lock
