---
title: Morgan Tracey
timezone: America/Phoenix
collections:
  posts:
    title: Posts
    output: true
    layout: posts
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: your-email@domain.com
description: The personal website of Morgan Tracey, US skeleton athlete, attorney,
  and wildland firefighter
url: https://morgantracey.github.io
locale: en
markdown: kramdown
permalink: "/:title"
show-social-links-in-footer: true
show-share-buttons: true

# Files
include:
- _pages
exclude:
- LICENSE
- README.md
- Gemfile
- Gemfile.lock
