# Site settings
title: Morgan Tracey
email: your-email@domain.com
description: "The personal website of Morgan Tracey, US skeleton athlete, attorney, and wildland firefighter"
url: "https://morgantracey.github.io" # the base hostname & protocol for your site
locale: "en"

# Build settings
markdown: kramdown
permalink: /:title

# Files
include:
  - _pages
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
