---
title: Morgan Tracey
timezone: America/Phoenix
collections:
  posts:
    title: Posts
    output: true
    layout: posts
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: morgan@morgantracey.us
description: The personal website of Morgan Tracey, US skeleton athlete, attorney,
  and wildland firefighter
url: http://www.morgantracey.us
locale: en
markdown: kramdown
permalink: "/:title"
tagline: From Lawsuit to Speedsuit
show-social-links-in-footer: true
show-share-buttons: true
quote: Carpe Diem
exclude:
- LICENSE
- README.md
- Gemfile
- Gemfile.lock
